version: "1.0"

services:
  julio-app:
    container_name: julio
    image: julio
    ports:
      - "8080:8080"
    networks:
      - julio-network

  julio-db:
    container_name: julio-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: julio
    ports:
      - "3308:3306"
    networks:
      - julio-network
volumes:
  julio-db:

networks:
  julio-network:
    driver: bridge
